# Generated by Django 5.1.1 on 2024-10-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('e_name', models.CharField(max_length=30)),
                ('e_sal', models.FloatField()),
                ('e_addr', models.CharField(max_length=40)),
                
            ],
        ),
    ]
