# Generated by Django 5.1.1 on 2024-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_addr',
            field=models.CharField(max_length=30),
        ),
    ]
